# TODO make configurable properties take values from env variables
spring:
  datasource:
    username:
    password:
    url:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate

app:
  auth:
    secret:
    expiration: