spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  servlet:
    multipart:
      max-file-size: ${MAX_MULTIPART_FILE_SIZE}
      max-request-size: ${MAX_MULTIPART_REQUEST_SIZE}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate

app:
  auth:
    secret: ${AUTH_SECRET}
    expiration: ${AUTH_EXPIRATION}